Repository justinmanigo/HMEZGEB, pull requests merged in 2022-10, with the labels that each got.

#224 Implement `Quick New` Transactions
  public/js/quick-new-shortcut.js
  resources/views/template/header.blade.php
  resources/views/template/navbar.blade.php
  resources/views/template/script.blade.php
  resources/views/vendors/bills/index.blade.php
  resources/views/vendors/payments/payment.blade.php
Labels: enhancement

#231 Make data types of currency values consistent to `decimal(18, 8)`
  database/migrations/2022_03_10_012743_create_taxes_table.php
  database/migrations/2022_03_10_035038_create_inventories_table.php
  database/migrations/2022_03_12_135618_create_chart_of_accounts_table.php
  database/migrations/2022_03_12_140648_create_period_of_accounts_table.php
  database/migrations/2022_03_12_142856_create_journal_postings_table.php
  database/migrations/2022_03_12_151738_create_receipt_items_table.php
  database/migrations/2022_03_12_153132_create_receipt_cash_transactions_table.php
  database/migrations/2022_03_12_154516_create_advance_revenues_table.php
  database/migrations/2022_03_12_155029_create_credit_receipts_table.php
  database/migrations/2022_03_12_155030_create_proformas_table.php
  database/migrations/2022_03_12_155657_create_receipts_table.php
  database/migrations/2022_03_13_092650_create_purchase_orders_table.php
  database/migrations/2022_03_13_104755_create_vat_payments_table.php
  database/migrations/2022_03_13_110624_create_withholding_payments_table.php
  database/migrations/2022_03_13_111155_create_bill_payments_table.php
  database/migrations/2022_03_13_111442_create_payroll_payments_table.php
  database/migrations/2022_03_13_150841_create_bills_table.php
  database/migrations/2022_04_10_121316_create_bill_items_table.php
  database/migrations/2022_04_12_070924_create_payrolls_table.php
  database/migrations/2022_04_12_071034_create_overtimes_table.php
  database/migrations/2022_04_12_071101_create_additions_table.php
  database/migrations/2022_04_12_071122_create_deductions_table.php
  database/migrations/2022_04_12_071202_create_loans_table.php
  database/migrations/2022_04_19_011649_create_overtime_payroll_rules_table.php
  database/migrations/2022_04_19_012228_create_income_tax_payroll_rules_table.php
  database/migrations/2022_04_20_044703_create_pension_payments_table.php
  database/migrations/2022_04_20_045356_create_income_tax_payments_table.php
  database/migrations/2022_06_02_070300_create_deposits_table.php
  database/migrations/2022_06_02_070301_create_transactions_table.php
  database/migrations/2022_06_02_153458_create_transfers_table.php
  database/migrations/2022_08_06_094831_create_pensions_table.php
  database/migrations/2022_08_06_095632_create_tax_payrolls_table.php
  database/migrations/2022_08_06_095651_create_basic_salaries_table.php
Labels: bug, enhancement, breaking

#232 Rework Payroll Generation
  app/Http/Controllers/PayrollController.php
  app/Models/PayrollPeriod.php
  database/migrations/2022_07_24_133731_create_payroll_periods_table.php
  resources/views/hr/payroll/index.blade.php
  resources/views/hr/payroll/show-employee.blade.php
  resources/views/hr/payroll/show.blade.php
  routes/web.php
Labels: enhancement, breaking

#237 Integrate COA and Loan Transactions
  app/Http/Controllers/LoanController.php
  app/Http/Requests/HumanResource/StoreLoanRequest.php
  app/Models/Loan.php
  database/migrations/2022_04_12_071202_create_loans_table.php
Labels: enhancement

#238 [Payroll] Link Payroll Period to COA
  app/Http/Controllers/PayrollController.php
  app/Http/Requests/HumanResource/StorePayrollRequest.php
  app/Models/PayrollPeriod.php
  database/migrations/2022_07_24_133731_create_payroll_periods_table.php
Labels: enhancement, breaking

#243 [Remerge] [Payroll] Link Payroll Period to COA
  app/Http/Controllers/PayrollController.php
  app/Models/PayrollPeriod.php
Labels: enhancement, breaking

#244 [Payroll Payment] Implement Feature
  app/Http/Controllers/PaymentsController.php
  app/Http/Controllers/PayrollController.php
  app/Http/Controllers/Settings/ChartOfAccountsController.php
  app/Http/Controllers/Vendors/Payments/PayrollPaymentController.php
  app/Http/Requests/HumanResource/StorePayrollRequest.php
  app/Http/Requests/Vendors/Payments/StorePayrollPaymentRequest.php
  app/Models/PaymentReferences.php
  app/Models/PayrollPayments.php
  app/Models/PayrollPeriod.php
  database/migrations/2022_03_12_155658_create_payment_references_table.php
  database/migrations/2022_03_13_111442_create_payroll_payments_table.php
  database/migrations/2022_07_24_133731_create_payroll_periods_table.php
  public/js/vendors/payment/select_payroll_payment.js
  public/js/vendors/template_select_cash_account.js
  public/js/vendors/template_select_payroll_period.js
  resources/views/hr/payroll/show.blade.php
  resources/views/template/navbar.blade.php
  resources/views/vendors/payments/forms/payrollPaymentModal.blade.php
  resources/views/vendors/payments/payment.blade.php
  routes/web.php
Labels: enhancement, breaking

#246 Add `reference_number` field for Proforma
  app/Http/Controllers/ReceiptController.php
  app/Http/Requests/Customer/Receipt/StoreProformaRequest.php
  app/Models/Proformas.php
  database/migrations/2022_03_12_155030_create_proformas_table.php
  resources/views/customer/receipt/forms/proforma.blade.php
Labels: enhancement, breaking

#247 Add `reference_number` field for Journal Voucher
  app/Actions/CreateJournalVoucher.php
  app/Http/Controllers/JournalVouchersController.php
  app/Http/Requests/StoreJournalVoucherRequest.php
  app/Models/JournalVouchers.php
  database/migrations/2022_03_12_142855_create_journal_vouchers_table.php
  resources/views/journals/index.blade.php
Labels: enhancement, breaking

#251 [Fix] Saving new beginning balance values wipes out existing journal postings
  app/Http/Controllers/Settings/ChartOfAccountsController.php
Labels: bug

#252 [Beginning Balance] Load beginning balance values from database on edit
  app/Http/Controllers/Settings/ChartOfAccountsController.php
  resources/views/settings/chart_of_account/index.blade.php
Labels: enhancement

#264 Reorganize `customers/receipts` modals
  resources/views/customer/receipt/forms/advance_revenue.blade.php
  resources/views/customer/receipt/forms/credit_receipt_updated.blade.php
  resources/views/customer/receipt/forms/proforma.blade.php
  resources/views/customer/receipt/forms/receipt.blade.php
  resources/views/customer/receipt/index.blade.php
  resources/views/customer/receipt/modals/actions/delete.blade.php
  resources/views/customer/receipt/modals/actions/export.blade.php
  resources/views/customer/receipt/modals/actions/import.blade.php
  resources/views/customer/receipt/modals/actions/mail.blade.php
  resources/views/customer/receipt/modals/actions/print.blade.php
  resources/views/customer/receipt/modals/actions/reactivate.blade.php
  resources/views/customer/receipt/modals/actions/void.blade.php
  resources/views/customer/receipt/modals/types/advance_revenue.blade.php
  resources/views/customer/receipt/modals/types/credit_receipt.blade.php
  resources/views/customer/receipt/modals/types/proforma.blade.php
  resources/views/customer/receipt/modals/types/receipt.blade.php
  resources/views/template/header.blade.php
Labels: enhancement

#265 [Feature] Implement Sales (`Customers/Receipts`)
  app/Http/Controllers/Customers/Receipts/SaleController.php
  app/Http/Controllers/ReceiptController.php
  app/Http/Requests/Customers/Receipts/StoreSaleRequest.php
  app/Models/Customers/Receipts/Sale.php
  app/Models/ReceiptReferences.php
  database/migrations/2022_03_12_151636_create_receipt_references_table.php
  database/migrations/2022_10_26_030938_create_sales_table.php
  public/js/customer/receipt/modal_sales.js
  public/js/customer/receipt/template_select_cash_account.js
  resources/views/customer/receipt/index.blade.php
  resources/views/customer/receipt/modals/types/sale.blade.php
  resources/views/template/navbar.blade.php
  routes/web.php
Labels: enhancement

#272 [JV] Fix Bug where COAs from other accounting systems appear in JV COA Selector & [Reports] Fix Inconsistencies in General Journal & Ledger
  app/Http/Controllers/ReportsController.php
  app/Http/Controllers/Settings/ChartOfAccountsController.php
Labels: bug

#274 Update payment type when price/discount changes in `Sale`
  public/js/customer/receipt/modal_sales.js
Labels: enhancement

#276 [Loan] Update Incorrect Credit Posting in successful transaction
  app/Http/Controllers/LoanController.php
  app/Http/Requests/HumanResource/StoreLoanRequest.php
  public/js/human_resource/modal_loan.js
  public/js/tagify_templates/template_select_cash_account.js
  resources/views/hr/loan/index.blade.php
Labels: bug

#280 [HR/Payroll] Fix error redirection when there are no employees for payroll generation
  app/Http/Controllers/PayrollController.php
Labels: bug
