Repository justinmanigo/HMEZGEB, pull requests merged in 2022-05, with the labels that each got.

#47 Implement Account Settings Page
  app/Http/Controllers/AccountSettingsController.php
  app/Http/Requests/Api/FormRequest.php
  app/Http/Requests/UpdateEmailRequest.php
  app/Http/Requests/UpdatePasswordRequest.php
  app/Http/Requests/UpdateUsernameRequest.php
  app/Models/User.php
  database/migrations/2014_10_12_000000_create_users_table.php
  database/seeders/UserTableSeeder.php
  public/js/account/update_info.js
  resources/views/account/index.blade.php
  resources/views/account/tabs/account.blade.php
  resources/views/template/header.blade.php
  resources/views/template/navbar.blade.php
  routes/web.php
Labels: enhancement

#49 Refactor Account Settings Module Structure and Implement Manage Users UI
  app/Http/Controllers/AccountSettings/ManageUsersController.php
  app/Http/Controllers/AccountSettings/YourAccountController.php
  public/js/account/update_yourAccount.js
  resources/views/account/manageUsers/index.blade.php
  resources/views/account/yourAccount/index.blade.php
  resources/views/template/account.blade.php
  resources/views/template/navbar.blade.php
  routes/web.php
Labels: enhancement

#40 Integrate `COA` and `Banks` in preparation for `Customer > Deposits` Implementation
  app/Http/Controllers/DepositController.php
  app/Http/Controllers/SettingChartOfAccountsController.php
  app/Models/ChartOfAccounts.php
  database/seeders/ChartOfAccountCategoriesTableSeeder.php
  public/js/customer/deposit/customer_deposit.js
  public/js/customer/deposit/template_select_bank.js
  public/js/settings/chart_of_accounts/select_coa_category.js
  resources/views/customer/deposit/index.blade.php
  resources/views/settings/chart_of_account/index.blade.php
  routes/web.php
Labels: enhancement

#52 Separate Account Settings and Manage Users
  app/Http/Controllers/AccountSettings/AccountSettingsController.php
  app/Http/Controllers/Settings/ManageUsersController.php
  public/js/account_settings/update_account_settings.js
  resources/views/account/yourAccount/index.blade.php
  resources/views/account_settings/index.blade.php
  resources/views/settings/users/index.blade.php
  resources/views/settings/users/manageUsers/editPermissions.blade.php
  resources/views/settings/users/manageUsers/index.blade.php
  resources/views/template/account.blade.php
  resources/views/template/navbar.blade.php
  routes/web.php
Labels: enhancement

#46 Implement some minor changes based on some tasks from April 22, 2022 Feedback Report
  app/Http/Controllers/EmployeeController.php
  app/Http/Controllers/InventoryController.php
  app/Http/Controllers/OvertimeController.php
  app/Http/Controllers/ReceiptController.php
  app/Models/Employee.php
  database/migrations/2022_03_12_151636_create_receipt_references_table.php
  database/migrations/2022_03_12_154516_create_advance_revenues_table.php
  database/migrations/2022_03_12_155029_create_credit_receipts_table.php
  database/migrations/2022_03_12_155030_create_proformas_table.php
  database/migrations/2022_03_12_155657_create_receipts_table.php
  database/migrations/2022_04_12_063858_create_employees_table.php
  database/migrations/2022_04_12_071034_create_overtimes_table.php
  public/js/customer/receipt/select_customer_receipt.js
  public/js/customer/receipt/select_proforma_receipt.js
  public/js/customer/receipt/template_select_proforma.js
  resources/views/banking/deposits/index.blade.php
  resources/views/customer/customer/edit.blade.php
  resources/views/customer/customer/index.blade.php
  resources/views/customer/deposit/index.blade.php
  resources/views/customer/receipt/forms/advance_revenue.blade.php
  resources/views/customer/receipt/forms/credit_receipt.blade.php
  resources/views/customer/receipt/forms/proforma.blade.php
  resources/views/customer/receipt/forms/receipt.blade.php
  resources/views/customer/receipt/index.blade.php
  resources/views/hr/employee/index.blade.php
  resources/views/hr/overtime/index.blade.php
  resources/views/inventory/forms/edit.blade.php
  resources/views/inventory/inventory.blade.php
  routes/web.php
Labels: bug, enhancement

#56 Integrate Module Permissions to Navbar
  app/Actions/CheckDuplicateSubModulePermission.php
  app/Actions/GetUserPermissions.php
  app/Http/Controllers/Settings/ManageUsersController.php
  database/seeders/ModulesTableSeeder.php
  resources/views/banking/accounts/index.blade.php
  resources/views/banking/transfers/index.blade.php
  resources/views/template/navbar.blade.php
  routes/web.php
Labels: enhancement

#58 Update POST-related Customer URLs
  app/Http/Controllers/CustomerController.php
  resources/views/customer/customer/edit.blade.php
  resources/views/customer/customer/index.blade.php
  routes/web.php
Labels: bug

#60 Implement Normal Referral Code Generation
  app/Http/Controllers/ReferralsController.php
  app/Http/Requests/StoreReferralRequest.php
  app/Http/Traits/HasReferralCode.php
  app/Models/Referral.php
  app/Models/Subscription.php
  app/Models/User.php
  composer.json
  composer.lock
  database/migrations/2022_02_04_013739_create_subscriptions_table.php
  database/migrations/2022_05_14_071921_create_referrals_table.php
  resources/views/referrals/index.blade.php
  resources/views/template/navbar.blade.php
  routes/web.php
Labels: enhancement, potentially-breaking

#61 Integrate Accounting Systems and User Permissions
  app/Actions/CheckDuplicateSubModulePermission.php
  app/Actions/GetAccountingSystemUserPermissions.php
  app/Actions/GetLoggedAccountingSystemUserId.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/Settings/ManageUsersController.php
  app/Models/AccountingSystemUser.php
  app/Models/Settings/Users/Permission.php
  app/Models/User.php
  database/migrations/2022_05_03_012948_create_permissions_table.php
  database/seeders/UserTableSeeder.php
  resources/views/settings/users/manageUsers/index.blade.php
  resources/views/template/navbar.blade.php
  routes/web.php
Labels: enhancement

#63 Implement Date Conversion from Gregorian to Ethiopian and Vice Versa
  app/Actions/ConvertEthiopianToGregorian.php
  app/Actions/ConvertGregorianToEthiopian.php
  composer.json
  composer.lock
Labels: documentation, enhancement, potentially-breaking

#65 Reorganize Routes
  routes/web.php
Labels: enhancement

#69 Redesign New Inventory Item UI and Add `Critical Quantity` and `Notify Critical Quantity` to New Inventory Item Form
  app/Http/Controllers/InventoryController.php
  app/Models/Inventory.php
  database/migrations/2022_02_10_035038_create_inventories_table.php
  resources/views/inventory/forms/newItem.blade.php
  resources/views/inventory/inventory.blade.php
Labels: enhancement

#72 Implement Form Validation and AJAX Usage for Receipts
  app/Http/Controllers/ReceiptController.php
  app/Http/Requests/Customer/Receipt/StoreAdvanceRevenueRequest.php
  app/Http/Requests/Customer/Receipt/StoreCreditReceiptRequest.php
  app/Http/Requests/Customer/Receipt/StoreProformaRequest.php
  app/Http/Requests/Customer/Receipt/StoreReceiptRequest.php
  public/js/ajax-submit-updated.js
  public/js/customer/receipt/select_item_proforma.js
  public/js/customer/receipt/select_item_receipt.js
  public/js/customer/receipt/select_receipt_creditreceipt.js
  resources/views/customer/receipt/forms/advance_revenue.blade.php
  resources/views/customer/receipt/forms/credit_receipt.blade.php
  resources/views/customer/receipt/forms/proforma.blade.php
  resources/views/customer/receipt/forms/receipt.blade.php
  resources/views/customer/receipt/index.blade.php
Labels: enhancement

#73 Implement Increase/Decrease of Quantity for Inventory
  app/Http/Controllers/BillsController.php
  app/Http/Controllers/InventoryController.php
  app/Http/Controllers/ReceiptController.php
  app/Http/Requests/Vendor/Bill/StoreBillRequest.php
  public/js/vendors/bill/select_item_bill.js
  resources/views/vendors/bills/forms/addBillModal.blade.php
  resources/views/vendors/bills/index.blade.php
Labels: enhancement

#74 Refactor `ReceiptController`
  app/Actions/Customer/Receipt/CreateReceiptReference.php
  app/Actions/Customer/Receipt/DeterminePaymentMethod.php
  app/Actions/Customer/Receipt/DetermineReceiptStatus.php
  app/Actions/Customer/Receipt/StoreReceiptItems.php
  app/Actions/Customer/Receipt/UpdateReceiptStatus.php
  app/Actions/UpdateInventoryItemQuantity.php
  app/Http/Controllers/ReceiptController.php
  app/Http/Requests/Customer/Receipt/StoreCreditReceiptRequest.php
Labels: enhancement

#75 Implement Improved Journal Voucher Form Validation
  app/Actions/CreateJournalPostings.php
  app/Actions/CreateJournalVoucher.php
  app/Http/Controllers/JournalVouchersController.php
  app/Http/Requests/StoreJournalVoucherRequest.php
  app/Models/JournalVouchers.php
  database/migrations/2022_03_12_142855_create_journal_vouchers_table.php
  public/js/journal_voucher/jv_functions.js
  resources/views/journals/index.blade.php
  resources/views/template/script.blade.php
Labels: enhancement

#77 Rework Referral and Subscription Models and Implement Referral Code Generation
  app/Actions/CreateReferral.php
  app/Http/Controllers/ReferralsController.php
  app/Http/Requests/Referral/GenerateReferralsRequest.php
  app/Http/Requests/StoreAdvancedReferralRequest.php
  app/Models/Referral.php
  app/Models/Subscription.php
  database/migrations/2022_02_03_071921_create_referrals_table.php
  database/migrations/2022_02_04_013739_create_subscriptions_table.php
  resources/views/referrals/index.blade.php
  routes/web.php
Labels: enhancement

#79 Modified Accounting Period Model to support Gregorian Date equivalents of Ethiopian Calendar
  app/Actions/GenerateAccountingPeriods.php
  app/Models/AccountingSystem.php
  app/Models/Settings/ChartOfAccounts/AccountingPeriods.php
  database/migrations/2022_02_04_015104_create_accounting_systems_table.php
  database/migrations/2022_03_12_135619_create_accounting_periods_table.php
  database/seeders/UserTableSeeder.php
  resources/views/template/navbar.blade.php
Labels: enhancement

#76 Separate Bank Account Fields to a Separate Model from COA and Implement Create and Read Bank Accounts for `Banking > Accounts`
  app/Http/Controllers/BankAccountsController.php
  app/Http/Controllers/DepositController.php
  app/Http/Controllers/Settings/ChartOfAccountsController.php
  app/Models/Accounts.php
  app/Models/BankAccounts.php
  app/Models/Settings/ChartOfAccounts/ChartOfAccounts.php
  database/migrations/2022_02_05_165245_create_accounts_table.php
  database/migrations/2022_03_12_135618_create_chart_of_accounts_table.php
  database/migrations/2022_03_15_051426_create_bank_accounts_table.php
  public/js/customer/deposit/template_select_bank.js
  public/js/journal_voucher/jv_functions.js
  public/js/journal_voucher/template_select_account.js
  resources/views/banking/accounts/index.blade.php
  resources/views/settings/chart_of_account/index.blade.php
  routes/web.php
Labels: enhancement
