Repository justinmanigo/HMEZGEB, pull requests merged in 2022-04, with the labels that each got.

#31 Implement Create/Read of `Settings > Chart of Accounts`
  app/Http/Controllers/SettingChartOfAccountsController.php
  app/Models/ChartOfAccountCategory.php
  app/Models/ChartOfAccounts.php
  app/Models/PeriodOfAccounts.php
  database/migrations/2022_03_12_135618_create_chart_of_account_categories_table.php
  database/migrations/2022_03_12_135618_create_chart_of_accounts_table.php
  database/migrations/2022_03_12_140648_create_period_of_accounts_table.php
  database/seeders/ChartOfAccountCategoriesTableSeeder.php
  database/seeders/DatabaseSeeder.php
  public/js/settings/chart_of_accounts/select_coa_category.js
  public/js/settings/chart_of_accounts/template_select_coa_category.js
  resources/views/settings/chart_of_account/index.blade.php
  routes/web.php
Labels: enhancement

#32 Implement `Settings > Taxes` CRUD
  app/Http/Controllers/TaxController.php
  app/Models/Tax.php
  database/migrations/2022_03_31_012743_create_taxes_table.php
  resources/views/settings/taxes/index.blade.php
  resources/views/template/navbar.blade.php
  routes/web.php
Labels: enhancement

#33 Implement `Human Resource > Employees` CRUD
  app/Http/Controllers/EmployeeController.php
  app/Models/Employee.php
  database/migrations/2022_03_15_035744_create_employees_table.php
  resources/views/hr/employee/index.blade.php
  routes/web.php
Labels: enhancement

#34 Implement `Journal Voucher` Form
  app/Http/Controllers/SettingChartOfAccountsController.php
  public/js/journal_voucher/select_account_jv.js
  public/js/journal_voucher/template_select_account.js
  resources/views/journals/index.blade.php
  routes/web.php
Labels: enhancement

#36 Fix bug on receipts/proforma when reselecting an item will accumulate total price
  public/js/customer/receipt/select_item_proforma.js
  public/js/customer/receipt/select_item_receipt.js
Labels: bug

#37 Implement Create/Read `Journal Voucher`
  app/Http/Controllers/JournalVouchersController.php
  app/Http/Controllers/SettingChartOfAccountsController.php
  app/Models/JournalEntries.php
  app/Models/JournalPostings.php
  app/Models/JournalVouchers.php
  database/migrations/2022_03_12_142840_create_journal_entries_table.php
  database/migrations/2022_03_12_142855_create_journal_vouchers_table.php
  database/migrations/2022_03_12_142856_create_journal_postings_table.php
  public/js/journal_voucher/jv_functions.js
  public/js/journal_voucher/select_account_jv.js
  public/js/journal_voucher/template_select_account.js
  resources/views/journals/index.blade.php
  resources/views/journals/show.blade.php
  resources/views/template/script.blade.php
  routes/web.php
Labels: enhancement

#38 Install `laravel-actions` package and refactor creation of `Journal Entries` and `Journal Postings`
  app/Actions/CreateJournalEntry.php
  app/Actions/CreateJournalPostings.php
  app/Actions/CreateJournalVoucher.php
  app/Http/Controllers/JournalVouchersController.php
  composer.json
  composer.lock
Labels: enhancement, breaking

#42 Implement Basic Functions for `Human Resource` Module
  app/Http/Controllers/AdditionController.php
  app/Http/Controllers/BillsController.php
  app/Http/Controllers/DeductionController.php
  app/Http/Controllers/EmployeeController.php
  app/Http/Controllers/LoanController.php
  app/Http/Controllers/OvertimeController.php
  app/Http/Controllers/PayrollController.php
  app/Http/Controllers/VendorsController.php
  app/Models/Addition.php
  app/Models/BillItem.php
  app/Models/Bills.php
  app/Models/Deduction.php
  app/Models/Employee.php
  app/Models/Loan.php
  app/Models/Overtime.php
  app/Models/PaymentReferences.php
  app/Models/Payroll.php
  composer.lock
  database/migrations/2022_03_13_150841_create_bills_table.php
  database/migrations/2022_04_06_121316_create_bill_items_table.php
  database/migrations/2022_04_12_063858_create_employees_table.php
  database/migrations/2022_04_12_070924_create_payrolls_table.php
  database/migrations/2022_04_12_071034_create_overtimes_table.php
  database/migrations/2022_04_12_071101_create_additions_table.php
  database/migrations/2022_04_12_071122_create_deductions_table.php
  database/migrations/2022_04_12_071202_create_loans_table.php
  public/js/human_resource/select_employee_addition.js
  public/js/human_resource/select_employee_deduction.js
  public/js/human_resource/select_employee_loan.js
  public/js/human_resource/select_employee_overtime.js
  public/js/human_resource/template_select_employee.js
  public/js/vendors/bill/select_item_bill.js
  public/js/vendors/bill/select_item_purchaseorder.js
  public/js/vendors/bill/select_vendor_bill.js
  public/js/vendors/bill/select_vendor_purchaseorder.js
  public/js/vendors/payment/select_payment_bill.js
  public/js/vendors/payment/select_vendor_bill.js
  public/js/vendors/payment/select_vendor_vat.js
  public/js/vendors/payment/select_vendor_withholding.js
  public/js/vendors/template_select_item.js
  public/js/vendors/template_select_vendor.js
  resources/views/hr/addition/index.blade.php
  resources/views/hr/deduction/index.blade.php
  resources/views/hr/employee/edit.blade.php
  resources/views/hr/employee/index.blade.php
  resources/views/hr/loan/index.blade.php
  resources/views/hr/overtime/index.blade.php
  resources/views/vendors/bills/forms/addBillModal.blade.php
  resources/views/vendors/bills/forms/purchaseOrderModal.blade.php
  resources/views/vendors/bills/index.blade.php
  resources/views/vendors/payments/forms/VATPaymentModal.blade.php
  resources/views/vendors/payments/forms/billPaymentModal.blade.php
  resources/views/vendors/payments/forms/withholdingPaymentModal.blade.php
  resources/views/vendors/payments/payment.blade.php
  routes/web.php
Labels: enhancement

#41 Integrate `Proforma` Field to DB on `Customer > Receipts > Receipts`
  app/Http/Controllers/ReceiptController.php
  app/Models/Inventory.php
  app/Models/ReceiptItem.php
  app/Models/ReceiptReferences.php
  public/js/customer/receipt/select_customer_proforma.js
  public/js/customer/receipt/select_customer_receipt.js
  public/js/customer/receipt/select_item_receipt.js
  public/js/customer/receipt/select_proforma_receipt.js
  public/js/customer/receipt/template_select_proforma.js
  resources/views/customer/receipt/forms/receipt.blade.php
  resources/views/customer/receipt/index.blade.php
  routes/web.php
Labels: enhancement

#39 Integrate `Taxes` to `Inventory > New Item` Form's `Tax` Field using Tagify Package
  app/Http/Controllers/InventoryController.php
  app/Models/Inventory.php
  database/migrations/2022_02_10_035038_create_inventories_table.php
  resources/views/inventory/forms/newItem.blade.php
Labels: enhancement
