Repository justinmanigo/HMEZGEB, pull requests merged in 2022-11, with the labels that each got.

#282 [Vendors/Bills] Implement COGS
  app/Http/Controllers/Vendors/Bills/CostOfGoodsSoldController.php
  app/Http/Requests/Vendors/Bills/StoreCostOfGoodsSoldRequest.php
  app/Models/Vendors/Bills/CostOfGoodsSold.php
  database/migrations/2022_10_31_121828_create_cost_of_goods_sold_table.php
  public/js/vendors/bill/default_values.js
  public/js/vendors/bill/modal_cogs.js
  resources/views/template/navbar.blade.php
  resources/views/vendors/bills/index.blade.php
  resources/views/vendors/bills/modals/types/cogs.blade.php
  routes/web.php
Labels: enhancement

#283 Update `Soon` and Add `New` Indicators in Quick New and New Dropdowns
  resources/views/customer/receipt/index.blade.php
  resources/views/template/navbar.blade.php
  resources/views/vendors/bills/index.blade.php
  resources/views/vendors/payments/payment.blade.php
Labels: enhancement

#284 [Vendor/Bills] Implement Expense
  app/Http/Controllers/Settings/ChartOfAccountsController.php
  app/Http/Controllers/Vendors/Bills/ExpenseController.php
  app/Http/Requests/Vendors/Bills/StoreExpenseRequest.php
  app/Models/Vendors/Bills/Expense.php
  app/Models/Vendors/Bills/ExpenseItem.php
  database/migrations/2022_11_01_061032_create_expenses_table.php
  database/migrations/2022_11_01_061103_create_expense_items_table.php
  public/js/tagify_templates/template_select_expense_account.js
  public/js/vendors/bill/default_values.js
  public/js/vendors/bill/modal_expense.js
  resources/views/template/navbar.blade.php
  resources/views/vendors/bills/index.blade.php
  resources/views/vendors/bills/modals/types/expense.blade.php
  routes/web.php
Labels: enhancement, breaking

#263 [Subscriptions] Make a search box that works for any data
  app/Http/Controllers/Control/SubscriptionController.php
  resources/views/control_panel/subscriptions/index.blade.php
Labels: enhancement

#260 [Subscription] Added view button and empty modal for user info
  resources/views/control_panel/subscriptions/index.blade.php
Labels: enhancement

#262 [Subscription] Add `Referred By` column by `username`
  app/Http/Controllers/Control/SubscriptionController.php
  resources/views/control_panel/subscriptions/index.blade.php
Labels: enhancement

#288 [Control Panel / Subscriptions] Implement View Subscription
  app/Http/Controllers/Control/SubscriptionController.php
  resources/views/control_panel/subscriptions/index.blade.php
  routes/web.php
Labels: enhancement

#291 [Vendors/Bill Payments] Rework Feature and Integrate to COA
  app/Http/Controllers/PaymentsController.php
  app/Http/Controllers/Vendors/Payments/BillPaymentController.php
  app/Http/Controllers/VendorsController.php
  app/Http/Requests/Vendors/Payments/StoreBillPaymentRequest.php
  public/js/tagify_templates/template_select_bill.js
  public/js/vendors/payment/select_vendor_billpayment_updated.js
  resources/views/vendors/bills/index.blade.php
  resources/views/vendors/payments/modals/types/bill_payment.blade.php
  resources/views/vendors/payments/payment.blade.php
  routes/web.php
Labels: enhancement

#296 [General] Periodically check authentication
  public/js/periodic-auth-check.js
  resources/views/template/script.blade.php
  resources/views/template/subscription/script.blade.php
  routes/web.php
Labels: enhancement

#298 [Referrals] Allow resending of emails and rejection of referral invitations
  app/Http/Controllers/ReferralsController.php
  app/Mail/Referral/InviteUser.php
  public/js/referrals/resend.js
  resources/views/referrals/index.blade.php
  resources/views/referrals/mail/invite-user.blade.php
  resources/views/referrals/reject.blade.php
  resources/views/referrals/show.blade.php
  routes/web.php
Labels: enhancement

#300 Focus Input On Load of Welcome Page and when navigating between Login and Signup Tabs
  resources/views/welcome.blade.php
Labels: enhancement

#301 [Vendors/Payments] Implement Income Tax Payment
  app/Http/Controllers/PaymentsController.php
  app/Http/Controllers/PayrollController.php
  app/Http/Controllers/Vendors/Payments/IncomeTaxPaymentController.php
  app/Http/Requests/Vendors/Payments/StoreIncomeTaxPaymentRequest.php
  app/Models/IncomeTaxPayments.php
  app/Models/PayrollPeriod.php
  database/migrations/2022_04_20_045356_create_income_tax_payments_table.php
  public/js/vendors/payment/modal_income_tax_payment.js
  public/js/vendors/payment/modal_payroll_payment.js
  resources/views/hr/payroll/show.blade.php
  resources/views/template/navbar.blade.php
  resources/views/vendors/payments/modals/types/income_tax_payment.blade.php
  resources/views/vendors/payments/payment.blade.php
  routes/web.php
Labels: enhancement, breaking

#305 [Vendor/Payments] Fix column name conflicts in payments table query
  app/Http/Controllers/PaymentsController.php
  resources/views/vendors/payments/payment.blade.php
Labels: bug

#306 [Welcome] Fix logo incorrectly referring to localhost instead of current host path
  resources/views/welcome.blade.php
Labels: bug, deployed

#308 [Vendors/Payments] Implement Withholding Payment and Implement Fixes on `BillsController`
  app/Actions/Vendors/Payments/GetAllWithholdingPeriods.php
  app/Actions/Vendors/Payments/Withholding/CheckIfWithholdingPeriodPaid.php
  app/Http/Controllers/BillsController.php
  app/Http/Controllers/PaymentsController.php
  app/Http/Controllers/Vendors/Bills/BillController.php
  app/Http/Controllers/Vendors/Bills/PurchaseOrderController.php
  app/Http/Controllers/Vendors/Payments/WithholdingPaymentController.php
  app/Http/Requests/Vendors/Bills/StoreBillRequest.php
  app/Http/Requests/Vendors/Bills/StoreCostOfGoodsSoldRequest.php
  app/Http/Requests/Vendors/Bills/StoreExpenseRequest.php
  app/Http/Requests/Vendors/Bills/StorePurchaseOrderRequest.php
  app/Http/Requests/Vendors/Payments/StoreWithholdingPaymentRequest.php
  app/Models/WithholdingPayments.php
  database/migrations/2022_03_13_110624_create_withholding_payments_table.php
  public/js/vendors/payment/modal_withholding_payment.js
  resources/views/template/navbar.blade.php
  resources/views/vendors/bills/forms/addBillModal.blade.php
  resources/views/vendors/bills/index.blade.php
  resources/views/vendors/payments/modals/types/withholding_payment.blade.php
  resources/views/vendors/payments/payment.blade.php
  routes/web.php
Labels: bug, enhancement

#310 [Vendors/Bills] Update Bill Modal UI and Allow Selection of Cash Accounts
  app/Http/Controllers/Vendors/Bills/BillController.php
  app/Http/Requests/Vendors/Bills/StoreBillRequest.php
  public/js/vendors/bill/default_values.js
  public/js/vendors/bill/modal_bill.js
  public/js/vendors/bill/select_item_bill.js
  resources/views/vendors/bills/index.blade.php
  resources/views/vendors/bills/modals/types/bill.blade.php
Labels: enhancement

#312 [Vendor/Payments] Add `Cash Account` Field Support for Bill Payments and Minor UI Tweaks
  app/Http/Controllers/Vendors/Payments/BillPaymentController.php
  app/Http/Requests/Vendors/Payments/StoreBillPaymentRequest.php
  public/js/vendors/payment/default_values.js
  public/js/vendors/payment/modal_bill_payment.js
  resources/views/vendors/payments/forms/billPaymentModal.blade.php
  resources/views/vendors/payments/modals/types/bill_payment.blade.php
  resources/views/vendors/payments/payment.blade.php
Labels: enhancement
